version="0.3.2"

[scripts]
# installations
rust="curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh"
brew='/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"'
zig='brew install zig'
surreal="brew install surrealdb/tap/surreal"
surreal-docker="docker run --rm --pull always -p 8000:8000 surrealdb/surrealdb:latest start"
